#!/usr/bin/python
#
# Copyright (c) 2011 Hugo Henriques Maia Vieira
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys, getopt
import os
from time import sleep
import pynotify
import subprocess

class Timer(object):

    SOUND_FILE = '/usr/share/sounds/timer.ogg'

    def __init__(self, minutes=0, seconds=0):
        try:
            self._minutes = int(minutes)
            self._seconds = int(seconds)
        except ValueError:
            raise ValueError, 'minutes and seconds should be numbers or numerical strings'

    def verbose_run(self):
        time = self._minutes * 60 + self._seconds
        for s in range(time):
            os.system('clear')
            minutes, seconds = divmod(time, 60)
            time -= 1
            print '%02d:%02d' % (minutes, seconds)
            sleep(1)
        self._notify()
        self._play_sound()

    def run(self):
        time = self._minutes * 60 + self._seconds
        for s in range(time):
            sleep(1)
        self._notify()
        self._play_sound()

    def _play_sound(self):
        subprocess.Popen(["paplay", Timer.SOUND_FILE])

    def _notify(self):
        pynotify.init('Timer')
        notification = pynotify.Notification("Time's up!",
                                             '%02d:%02d has passed'
                                                % (self._minutes,self._seconds),
                                             'dialog-ok')
        notification.show()


def main(argv):
    try:
        minutes, seconds = format_time(argv[0])
        opts, args = getopt.getopt(argv[1:], 'hv', ['help', 'verbose'])
    except ValueError, e:
        print '\n\targument error: %s' % e
        usage()
        sys.exit(2)
    except: # getopt.GetoptError or IndexError
        usage()
        sys.exit(2)
    verbose = False
    for opt, arg in opts:
        if opt in ('-h', '--help'): usage(); exit()
        elif opt in ('-v', '--verbose'): verbose = True
    timer = Timer(minutes, seconds)
    timer.verbose_run() if verbose else timer.run()
    sys.exit()

def usage():
    print """\n\tusage: ticktimer (minutes|minutes:seconds) [-h|--help] [-v|--verbose]\n"""

def format_time(time):
    """Return a [minutes, seconds] integer list."""
    time = time.split(':')
    if len(time) == 1: return [int(time[0]), 0]
    elif len(time) == 2: return map(int, time)
    raise ValueError, 'the time should be like 5 (just minutes) or 5:30 (minutes:seconds)'

if __name__ == '__main__':
    main(sys.argv[1:])

